//! Stable project tasks and their evidence-derived state.
//!
//! Task records contain intent and links, never a writable status. Every view
//! calls [`view`] so TASKS.md, context, plans and the talk screen use the same
//! projection.

use std::collections::BTreeSet;
use std::io::Write;
use std::path::PathBuf;

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};

use crate::contracts::{FailureClass, RoundPhase};
use crate::project::{self, Project, write_atomic};

pub(crate) const STATES: [&str; 5] = ["finished", "reviewed", "merged", "installed", "verified"];
const GENERATED_NOTICE: &str = "<!-- Generated from tasks/*.toml. Do not edit this file. -->";
const PRESERVED_PREFIX: &str = "<!-- Preserved hand-written TASKS.md: ";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct DatedNote {
    /// Empty on historical notes written before provenance was required.
    #[serde(default)]
    pub(crate) id: String,
    pub(crate) at: String,
    /// The request id behind this note. Empty historical notes are displayed
    /// as undated rather than being assigned guessed authority.
    #[serde(default)]
    pub(crate) request: String,
    pub(crate) text: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) replaces: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct Evidence {
    pub(crate) at: String,
    pub(crate) command: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) acceptance: Vec<usize>,
    /// Installation evidence is machine-specific. Historical and verification
    /// evidence has no machine.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) machine: Option<String>,
    /// The exact repository commit carried by that machine's build.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) build: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub(crate) struct RunningEvidence {
    pub(crate) at: String,
    pub(crate) command: String,
    pub(crate) machines: Vec<String>,
    pub(crate) processes: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
pub(crate) struct Task {
    pub(crate) schema: u32,
    pub(crate) id: String,
    pub(crate) title: String,
    /// `request:<id>` or `ask:<id>@<revision>`, all validated at creation.
    pub(crate) authority: Vec<String>,
    pub(crate) acceptance: Vec<String>,
    /// An explicit older note, instruction, decision or task this task supersedes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) replaces: Option<String>,
    pub(crate) notes: Vec<DatedNote>,
    pub(crate) attempts: Vec<String>,
    pub(crate) rounds: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) plan_step: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) repo: Option<String>,
    pub(crate) installed: Vec<Evidence>,
    /// A successful check that every running harness process uses an installed
    /// image. This is deliberately separate from acceptance verification.
    #[serde(default)]
    pub(crate) running: Vec<RunningEvidence>,
    pub(crate) verified: Vec<Evidence>,
    pub(crate) created: String,
}

impl Default for Task {
    fn default() -> Self {
        Self {
            schema: 1,
            id: String::new(),
            title: String::new(),
            authority: Vec::new(),
            acceptance: Vec::new(),
            replaces: None,
            notes: Vec::new(),
            attempts: Vec::new(),
            rounds: Vec::new(),
            plan_step: None,
            repo: None,
            installed: Vec::new(),
            running: Vec::new(),
            verified: Vec::new(),
            created: String::new(),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub(crate) enum State {
    Open,
    Working,
    Finished,
    Reviewed,
    Merged,
    Installed,
    Verified,
    Failed,
    Cancelled,
    Unknown,
}

impl State {
    pub(crate) fn word(self) -> &'static str {
        match self {
            Self::Open => "open",
            Self::Working => "working",
            Self::Finished => "finished",
            Self::Reviewed => "reviewed",
            Self::Merged => "merged",
            Self::Installed => "installed",
            Self::Verified => "verified",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
            Self::Unknown => "unknown",
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct View {
    pub(crate) record: Task,
    pub(crate) state: State,
    pub(crate) next: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) failure_class: Option<FailureClass>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) provider_kind: Option<String>,
}

impl View {
    pub(crate) fn terminal(&self, project: &Project) -> bool {
        if self.state == State::Cancelled {
            return true;
        }
        required_states(project, &self.record)
            .ok()
            .and_then(|states| states.last().cloned())
            .is_some_and(|last| last == self.state.word())
    }
}

fn dir(project: &Project) -> PathBuf {
    project.dir().join("tasks")
}

fn path(project: &Project, id: &str) -> PathBuf {
    dir(project).join(format!("{id}.toml"))
}

pub(crate) fn validate_id(id: &str) -> Result<()> {
    let digits = id.strip_prefix("job-").unwrap_or("");
    if digits.len() < 4 || !digits.chars().all(|c| c.is_ascii_digit()) {
        bail!("task_id: `{id}` is not a task id (expected job-0001)");
    }
    Ok(())
}

pub(crate) fn load(project: &Project, id: &str) -> Result<Task> {
    validate_id(id)?;
    let file = path(project, id);
    let text = match std::fs::read_to_string(&file) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err(crate::refusal::error(format!(
                "task_unknown: no task `{id}` in `{}`",
                project.slug
            )));
        }
        Err(error) => {
            return Err(error).with_context(|| format!("could not read {}", file.display()));
        }
    };
    let task: Task = toml::from_str(&text)
        .with_context(|| format!("task_unreadable: {} does not parse", file.display()))?;
    validate_record(&task)?;
    if task.id != id {
        bail!(
            "task_identity: {} contains `{}` instead of `{id}`",
            file.display(),
            task.id
        );
    }
    Ok(task)
}

fn validate_record(task: &Task) -> Result<()> {
    if task.schema != 1 {
        bail!("task_schema: expected 1, got {}", task.schema);
    }
    validate_id(&task.id)?;
    if task.title.trim().is_empty() {
        bail!("task_title: the title is empty");
    }
    if task.authority.is_empty() {
        bail!("task_authority: at least one request or answered ask is required");
    }
    if task.acceptance.is_empty() || task.acceptance.iter().any(|line| line.trim().is_empty()) {
        bail!("task_acceptance: at least one plain acceptance condition is required");
    }
    Ok(())
}

fn write(project: &Project, task: &Task) -> Result<()> {
    validate_record(task)?;
    write_atomic(&path(project, &task.id), toml::to_string(task)?.as_bytes())
}

fn next_id(project: &Project) -> Result<String> {
    let mut highest = 0_u64;
    for entry in std::fs::read_dir(dir(project))? {
        let entry = entry?;
        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        let Some(id) = name.strip_suffix(".toml") else {
            continue;
        };
        if validate_id(id).is_err() {
            continue;
        }
        let number = id
            .strip_prefix("job-")
            .expect("validated task id")
            .parse::<u64>()
            .with_context(|| format!("task_id: `{id}` is too large"))?;
        highest = highest.max(number);
    }
    let next = highest
        .checked_add(1)
        .context("task_id: the task id space is exhausted")?;
    Ok(format!("job-{next:04}"))
}

pub(crate) fn list_with_errors(project: &Project) -> (Vec<Task>, Vec<anyhow::Error>) {
    let entries = match std::fs::read_dir(dir(project)) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return (Vec::new(), Vec::new());
        }
        Err(error) => return (Vec::new(), vec![error.into()]),
    };
    let mut tasks = Vec::new();
    let mut errors = Vec::new();
    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => {
                errors.push(error.into());
                continue;
            }
        };
        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            errors.push(anyhow::anyhow!(
                "task_unreadable: a task file name is not UTF-8"
            ));
            continue;
        };
        let Some(id) = name.strip_suffix(".toml") else {
            continue;
        };
        match load(project, id) {
            Ok(task) => tasks.push(task),
            Err(error) => errors.push(error),
        }
    }
    tasks.sort_by(|a, b| a.id.cmp(&b.id));
    (tasks, errors)
}

pub(crate) fn add(
    project: &Project,
    title: &str,
    authority: Vec<String>,
    acceptance: Vec<String>,
    repo: Option<String>,
    plan_step: Option<String>,
    replaces: Option<String>,
) -> Result<Task> {
    if title.trim().is_empty() {
        return Err(crate::refusal::error(
            "task_title: a plain title is required",
        ));
    }
    if authority.is_empty() {
        return Err(crate::refusal::error(
            "task_authority: pass at least one --request request:<id> or ask:<id>@<revision>",
        ));
    }
    if acceptance.is_empty() || acceptance.iter().any(|line| line.trim().is_empty()) {
        return Err(crate::refusal::error(
            "task_acceptance: pass at least one non-empty --acceptance sentence",
        ));
    }
    let title = crate::glossary::check_record_sentence(project, "task title", title)?;
    let mut checked_acceptance = Vec::new();
    for (index, condition) in acceptance.iter().enumerate() {
        checked_acceptance.push(crate::glossary::check_record_sentence(
            project,
            &format!("acceptance condition {}", index + 1),
            condition,
        )?);
    }
    for reference in &authority {
        if let Err(error) = crate::decide::validate_basis(project, reference) {
            return Err(crate::refusal::error(format!(
                "task_authority: `{reference}` does not name existing authority: {error:#}"
            )));
        }
    }
    if let Some(old) = replaces.as_deref() {
        if !crate::note::target_exists(project, old) {
            return Err(crate::refusal::error(format!(
                "task_replacement: no note, decision or task `{old}` exists"
            )));
        }
        let rows = crate::note::rows(project);
        if crate::note::replacement_map(&rows).contains_key(old) {
            return Err(crate::refusal::error(format!(
                "task_replacement: `{old}` already has a replacement"
            )));
        }
    }
    if let Some(step) = plan_step.as_deref() {
        let plan = crate::plan::load(project)?
            .ok_or_else(|| crate::refusal::error("task_plan: no plan is written down"))?;
        if !plan.steps.iter().any(|candidate| candidate.id == step) {
            return Err(crate::refusal::error(format!(
                "task_plan: no plan step `{step}`"
            )));
        }
    }
    let repo = repo.map(|repo| {
        std::fs::canonicalize(&repo)
            .or_else(|_| std::path::absolute(&repo))
            .map(|path| path.to_string_lossy().into_owned())
            .unwrap_or(repo)
    });
    let _lock = project.lock()?;
    std::fs::create_dir_all(dir(project))?;
    let task = Task {
        id: next_id(project)?,
        title,
        authority,
        acceptance: checked_acceptance,
        replaces,
        plan_step,
        repo,
        created: project::now(),
        ..Task::default()
    };
    write(project, &task)?;
    drop(_lock);
    refresh_tasks_md(project)?;
    Ok(task)
}

fn update(
    project: &Project,
    id: &str,
    change: impl FnOnce(&mut Task) -> Result<()>,
) -> Result<Task> {
    let _lock = project.lock()?;
    let mut task = load(project, id)?;
    change(&mut task)?;
    write(project, &task)?;
    drop(_lock);
    refresh_tasks_md(project)?;
    Ok(task)
}

pub(crate) fn note(
    project: &Project,
    id: &str,
    text: &str,
    request: &str,
    replaces: Option<&str>,
) -> Result<Task> {
    if text.trim().is_empty() {
        return Err(crate::refusal::error("task_note: a note is required"));
    }
    let request = request.strip_prefix("request:").unwrap_or(request);
    crate::decide::validate_basis(project, &format!("request:{request}"))?;
    if let Some(old) = replaces {
        if !crate::note::target_exists(project, old) {
            bail!("task_note_replacement: no note `{old}` exists");
        }
        let rows = crate::note::rows(project);
        if crate::note::replacement_map(&rows).contains_key(old) {
            bail!("task_note_replacement: `{old}` already has a replacement");
        }
    }
    update(project, id, |task| {
        let next = task.notes.len() + 1;
        task.notes.push(DatedNote {
            id: format!("{id}:note-{next:04}"),
            at: project::now(),
            request: request.to_string(),
            text: text.trim().to_string(),
            replaces: replaces.map(str::to_string),
        });
        Ok(())
    })
}

pub(crate) fn link_attempt(project: &Project, id: &str, thread: &str) -> Result<Task> {
    crate::thread::load(project, thread)
        .with_context(|| format!("task_attempt: no thread `{thread}`"))?;
    for other in list_with_errors(project).0 {
        if other.id != id && other.attempts.iter().any(|attempt| attempt == thread) {
            return Err(crate::refusal::error(format!(
                "task_attempt: `{thread}` already belongs to `{}`",
                other.id
            )));
        }
    }
    let task = update(project, id, |task| {
        if !task.attempts.iter().any(|attempt| attempt == thread) {
            task.attempts.push(thread.to_string());
        }
        Ok(())
    })?;
    for round in crate::round::list(project)
        .into_iter()
        .filter(|round| round.carries(thread))
    {
        link_round_for_thread(project, &round.round, thread)?;
    }
    load(project, &task.id)
}

/// Attach a historical thread and every round carrying it to a stable task.
/// Unlike an ordinary start, adoption also establishes the task repository
/// when the task did not have one yet.
pub(crate) fn adopt(project: &Project, id: &str, thread_id: &str) -> Result<Task> {
    let thread = crate::thread::load(project, thread_id)
        .with_context(|| format!("task_adopt: no thread `{thread_id}`"))?;
    let _lock = project.lock()?;
    for task in list_with_errors(project).0 {
        if task.attempts.iter().any(|attempt| attempt == thread_id) {
            return Err(crate::refusal::error(format!(
                "task_adopt_linked: `{thread_id}` already belongs to `{}`",
                task.id
            )));
        }
    }
    let mut task = load(project, id)?;
    if let Some(repo) = task.repo.as_deref() {
        let expected = std::fs::canonicalize(repo).unwrap_or_else(|_| PathBuf::from(repo));
        let actual =
            std::fs::canonicalize(&thread.repo).unwrap_or_else(|_| PathBuf::from(&thread.repo));
        if expected != actual {
            return Err(crate::refusal::error(format!(
                "task_adopt_repository: `{thread_id}` works in `{}`, not `{repo}`",
                thread.repo
            )));
        }
    }
    if task.repo.is_none() && !thread.repo.is_empty() {
        task.repo = Some(thread.repo.clone());
    }
    task.attempts.push(thread_id.to_string());
    write(project, &task)?;
    drop(_lock);
    refresh_tasks_md(project)?;
    for round in crate::round::list(project)
        .into_iter()
        .filter(|round| round.carries(thread_id))
    {
        link_round_for_thread(project, &round.round, thread_id)?;
    }
    load(project, &task.id)
}

pub(crate) fn link_round_for_thread(project: &Project, round: &str, thread: &str) -> Result<()> {
    if let Some(task) = list_with_errors(project)
        .0
        .into_iter()
        .find(|task| task.attempts.iter().any(|attempt| attempt == thread))
    {
        update(project, &task.id, |task| {
            if !task.rounds.iter().any(|candidate| candidate == round) {
                task.rounds.push(round.to_string());
            }
            Ok(())
        })?;
    }
    Ok(())
}

fn validate_states(states: &[String]) -> Result<()> {
    if states.is_empty() || states.first().map(String::as_str) != Some("finished") {
        bail!("task_states: the ordered list must start with `finished`");
    }
    let mut previous = None;
    for state in states {
        let index = STATES
            .iter()
            .position(|candidate| candidate == state)
            .with_context(|| format!("task_states: `{state}` is not a task milestone"))?;
        if previous.is_some_and(|old| index <= old) {
            bail!("task_states: milestones must be unique and in evidence order");
        }
        previous = Some(index);
    }
    Ok(())
}

pub(crate) fn required_states(project: &Project, task: &Task) -> Result<Vec<String>> {
    let settings = project.read_project_md()?.0;
    let states = task
        .repo
        .as_deref()
        .and_then(|repo| settings.repos.iter().find(|row| row.path == repo))
        .filter(|row| !row.task_states.is_empty())
        .map(|row| row.task_states.clone())
        .unwrap_or(settings.task_states);
    validate_states(&states)?;
    Ok(states)
}

fn running_current(task: &Task) -> bool {
    let latest_install = task.installed.iter().map(|evidence| &evidence.at).max();
    let latest_running = task.running.iter().map(|evidence| &evidence.at).max();
    latest_install
        .is_none_or(|installed| latest_running.is_some_and(|running| running >= installed))
}

fn next_for(state: State, required: &[String], task: &Task) -> String {
    match state {
        State::Open => "start an attempt".into(),
        State::Working => "finish the current attempt".into(),
        State::Failed => "retry or cancel the current attempt".into(),
        State::Cancelled => "none".into(),
        State::Unknown => "repair the unreadable evidence".into(),
        _ => {
            let at = required
                .iter()
                .position(|candidate| *candidate == state.word());
            match at
                .and_then(|index| required.get(index + 1))
                .map(String::as_str)
            {
                Some("reviewed") => "put the attempt in a review round".into(),
                Some("merged") => "merge its reviewed round".into(),
                Some("installed") => "record installation evidence".into(),
                Some("verified") if !running_current(task) => {
                    "check the running harness processes".into()
                }
                Some("verified") => {
                    let done: BTreeSet<usize> = task
                        .verified
                        .iter()
                        .flat_map(|evidence| evidence.acceptance.iter().copied())
                        .collect();
                    format!(
                        "verify {} acceptance condition(s)",
                        task.acceptance.len().saturating_sub(done.len())
                    )
                }
                Some(other) => format!("record {other} evidence"),
                None => "none".into(),
            }
        }
    }
}

pub(crate) fn view(project: &Project, task: Task) -> View {
    let required = match required_states(project, &task) {
        Ok(required) => required,
        Err(_) => {
            return View {
                record: task,
                state: State::Unknown,
                next: "repair the task state configuration".into(),
                failure_class: None,
                provider_kind: None,
            };
        }
    };
    if task.attempts.is_empty() {
        return View {
            record: task,
            state: State::Open,
            next: "start an attempt".into(),
            failure_class: None,
            provider_kind: None,
        };
    }
    let current = task.attempts.last().expect("attempt checked");
    let thread = match crate::thread::load(project, current) {
        Ok(thread) => thread,
        Err(_) => {
            return View {
                record: task,
                state: State::Unknown,
                next: "repair the missing attempt record".into(),
                failure_class: None,
                provider_kind: None,
            };
        }
    };
    let event_dir = project.dir().join("events");
    let events_readable = std::fs::read_dir(&event_dir)
        .map(|entries| {
            entries
                .flatten()
                .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "toml"))
                .all(|entry| {
                    std::fs::read_to_string(entry.path())
                        .ok()
                        .and_then(|text| toml::from_str::<crate::contracts::Event>(&text).ok())
                        .is_some()
                })
        })
        .unwrap_or_else(|error| error.kind() == std::io::ErrorKind::NotFound);
    if !events_readable {
        return View {
            record: task,
            state: State::Unknown,
            next: "repair the unreadable event evidence".into(),
            failure_class: None,
            provider_kind: None,
        };
    }
    let events = crate::events::list(project);
    let event = crate::round::latest_event(&events, current, thread.attempt.max(1));
    if thread.status == crate::thread::Status::Resolved && !thread.cancellation_reason.is_empty() {
        return View {
            record: task,
            state: State::Cancelled,
            next: "none".into(),
            failure_class: None,
            provider_kind: None,
        };
    }
    if let Some(failed) = event.and_then(|event| event.payload.failed.as_ref()) {
        return View {
            record: task,
            state: State::Failed,
            next: "retry or cancel the current attempt".into(),
            failure_class: Some(failed.class),
            provider_kind: failed.provider_kind.clone(),
        };
    }
    if let Some(waiting) = event.and_then(|event| event.payload.waiting.as_ref()) {
        return View {
            record: task,
            state: State::Working,
            next: format!("wait for Rolf: {}", waiting.text.trim()),
            failure_class: None,
            provider_kind: None,
        };
    }
    if thread.status == crate::thread::Status::Failed {
        return View {
            record: task,
            state: State::Failed,
            next: "retry or cancel the current attempt".into(),
            failure_class: Some(thread.failure_class),
            provider_kind: thread.provider_failure_kind.clone(),
        };
    }
    if event
        .and_then(|event| event.payload.done.as_ref())
        .is_none()
    {
        return View {
            record: task,
            state: State::Working,
            next: "finish the current attempt".into(),
            failure_class: None,
            provider_kind: None,
        };
    }

    let mut relevant = Vec::new();
    for id in &task.rounds {
        let round = match crate::round::load(project, id) {
            Ok(round) => round,
            Err(_) => {
                return View {
                    record: task,
                    state: State::Unknown,
                    next: "repair the unreadable round evidence".into(),
                    failure_class: None,
                    provider_kind: None,
                };
            }
        };
        if round
            .manifest
            .members
            .iter()
            .any(|member| member.thread == *current)
        {
            relevant.push(round);
        }
    }
    if relevant.iter().any(|round| {
        round.verdict.is_some()
            && round.phase == RoundPhase::VerdictIn
            && round.verdict_kind.is_none()
    }) {
        return View {
            record: task,
            state: State::Unknown,
            next: "read the review verdict evidence".into(),
            failure_class: None,
            provider_kind: None,
        };
    }
    let reviewed = relevant.iter().any(|round| {
        round.verdict_kind.as_deref() == Some("MERGE")
            || matches!(
                round.phase,
                RoundPhase::Merging | RoundPhase::Checkpointing | RoundPhase::Merged
            )
    });
    let merged = relevant
        .iter()
        .any(|round| round.phase == RoundPhase::Merged);
    let verified: BTreeSet<usize> = task
        .verified
        .iter()
        .flat_map(|evidence| evidence.acceptance.iter().copied())
        .collect();
    let all_verified = (1..=task.acceptance.len()).all(|index| verified.contains(&index));
    let facts = |state: &str| match state {
        "finished" => true,
        "reviewed" => reviewed,
        "merged" => merged,
        "installed" => !task.installed.is_empty(),
        "verified" => {
            all_verified
                && (!required.iter().any(|state| state == "installed") || running_current(&task))
        }
        _ => false,
    };
    let mut state = State::Finished;
    for milestone in &required {
        if !facts(milestone) {
            break;
        }
        state = match milestone.as_str() {
            "finished" => State::Finished,
            "reviewed" => State::Reviewed,
            "merged" => State::Merged,
            "installed" => State::Installed,
            "verified" => State::Verified,
            _ => State::Unknown,
        };
    }
    let next = next_for(state, &required, &task);
    View {
        record: task,
        state,
        next,
        failure_class: None,
        provider_kind: None,
    }
}

pub(crate) fn views(project: &Project) -> (Vec<View>, Vec<anyhow::Error>) {
    let (tasks, errors) = list_with_errors(project);
    (
        tasks.into_iter().map(|task| view(project, task)).collect(),
        errors,
    )
}

#[derive(Debug, Clone, Copy, clap::ValueEnum)]
pub(crate) enum EvidenceKind {
    Verified,
}

pub(crate) fn record_evidence(
    project: &Project,
    id: &str,
    kind: EvidenceKind,
    command: &str,
    acceptance: Vec<usize>,
) -> Result<Task> {
    if command.trim().is_empty() {
        return Err(crate::refusal::error(
            "task_evidence: --command is required",
        ));
    }
    let before = view(project, load(project, id)?);
    let required = required_states(project, &before.record)?;
    let word = "verified";
    if !required.iter().any(|state| state == word) {
        return Err(crate::refusal::error(format!(
            "task_evidence: `{word}` is not enabled for this task's repository"
        )));
    }
    let prerequisite = if required.iter().any(|state| state == "installed") {
        "installed"
    } else {
        "merged"
    };
    let reached = STATES
        .iter()
        .position(|state| *state == before.state.word())
        .unwrap_or(0);
    let needed = STATES
        .iter()
        .position(|state| *state == prerequisite)
        .unwrap_or(usize::MAX);
    if reached < needed {
        return Err(crate::refusal::error(format!(
            "task_evidence: task is {}, but `{word}` needs it to be {prerequisite}",
            before.state.word()
        )));
    }
    if required.iter().any(|state| state == "installed") && !running_current(&before.record) {
        return Err(crate::refusal::error(
            "task_evidence: verification needs a successful running-processes check after installation",
        ));
    }
    if acceptance.is_empty() {
        return Err(crate::refusal::error(
            "task_evidence: verification needs at least one --acceptance number",
        ));
    }
    if acceptance
        .iter()
        .any(|index| *index == 0 || *index > before.record.acceptance.len())
    {
        return Err(crate::refusal::error(format!(
            "task_evidence: an acceptance number is outside 1..={}",
            before.record.acceptance.len()
        )));
    }
    let mut acceptance = acceptance;
    acceptance.sort_unstable();
    acceptance.dedup();
    update(project, id, |task| {
        let evidence = Evidence {
            at: project::now(),
            command: command.trim().to_string(),
            acceptance,
            machine: None,
            build: None,
        };
        let EvidenceKind::Verified = kind;
        task.verified.push(evidence);
        Ok(())
    })
}

/// Record one machine's installed build without asking the coordinator to
/// translate a successful install back into task state.
pub(crate) fn record_installed(
    project: &Project,
    id: &str,
    machine: &str,
    build: &str,
) -> Result<Task> {
    update(project, id, |task| {
        task.installed.push(Evidence {
            at: project::now(),
            command: "ha harness install".into(),
            acceptance: Vec::new(),
            machine: Some(machine.to_string()),
            build: Some(build.to_string()),
        });
        Ok(())
    })
}

pub(crate) fn record_running(
    project: &Project,
    id: &str,
    machines: Vec<String>,
    processes: Vec<String>,
) -> Result<Task> {
    update(project, id, |task| {
        task.running.push(RunningEvidence {
            at: project::now(),
            command: "ha harness install".into(),
            machines,
            processes,
        });
        Ok(())
    })
}

fn preserved_tasks_path(text: &[u8]) -> Option<String> {
    std::str::from_utf8(text).ok()?.lines().find_map(|line| {
        line.strip_prefix(PRESERVED_PREFIX)
            .and_then(|path| path.strip_suffix(" -->"))
            .map(str::to_string)
    })
}

/// Save a hand-written task list before the first generated view replaces it.
/// `create_new` makes concurrent refreshes converge on one identical archive.
fn archive_handwritten_tasks(project: &Project, contents: &[u8]) -> Result<String> {
    let archive = project.dir().join("memory/archive");
    std::fs::create_dir_all(&archive)
        .with_context(|| format!("could not create {}", archive.display()))?;
    let date = project::now().get(..10).unwrap_or("undated").to_string();
    for suffix in 1_u64.. {
        let suffix = if suffix == 1 {
            String::new()
        } else {
            format!("-{suffix}")
        };
        let name = format!("TASKS-before-generated-{date}{suffix}.md");
        let path = archive.join(&name);
        if let Ok(saved) = std::fs::read(&path) {
            if saved == contents {
                return Ok(format!("memory/archive/{name}"));
            }
            continue;
        }
        match std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
        {
            Ok(mut file) => {
                file.write_all(contents)?;
                file.sync_all()?;
                return Ok(format!("memory/archive/{name}"));
            }
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("could not preserve {}", path.display()));
            }
        }
    }
    unreachable!("the archive suffix is unbounded")
}

pub(crate) fn refresh_tasks_md(project: &Project) -> Result<()> {
    let (views, errors) = views(project);
    // Existing projects own hand-written TASKS.md files. Do not touch one until
    // a stable task record actually exists and there is a generated view to
    // replace it with.
    if views.is_empty() && errors.is_empty() {
        return Ok(());
    }

    let tasks_path = project.dir().join("TASKS.md");
    let existing = match std::fs::read(&tasks_path) {
        Ok(contents) => Some(contents),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => {
            return Err(error).with_context(|| format!("could not read {}", tasks_path.display()));
        }
    };
    let mut preserved = existing.as_deref().and_then(preserved_tasks_path);
    if let Some(contents) = existing.as_deref()
        && !contents
            .windows(GENERATED_NOTICE.len())
            .any(|window| window == GENERATED_NOTICE.as_bytes())
    {
        preserved = Some(archive_handwritten_tasks(project, contents)?);
    }

    let mut text = format!("# Tasks\n\n{GENERATED_NOTICE}\n");
    if let Some(path) = preserved {
        text.push_str(&format!(
            "{PRESERVED_PREFIX}{path} -->\nPrevious hand-written task list: `{path}`.\n"
        ));
    }
    for (heading, terminal) in [("Open", false), ("Complete", true)] {
        text.push_str(&format!("\n## {heading}\n"));
        let mut any = false;
        for view in &views {
            if view.terminal(project) != terminal {
                continue;
            }
            any = true;
            let mark = if terminal { "x" } else { " " };
            text.push_str(&format!(
                "- [{mark}] `{}` {} — {}; next: {}\n",
                view.record.id,
                view.record.title,
                view.state.word(),
                view.next
            ));
        }
        if !any {
            text.push('\n');
        }
    }
    if !errors.is_empty() {
        text.push_str("\n## Unknown\n");
        for error in errors {
            text.push_str(&format!("- [ ] unreadable task — unknown ({error:#})\n"));
        }
    }
    write_atomic(&tasks_path, text.as_bytes())
}

pub(crate) fn render(view: &View) -> String {
    let mut out = format!(
        "{} [{}] {}\nnext: {}\n",
        view.record.id,
        view.state.word(),
        view.record.title,
        view.next
    );
    out.push_str(&format!(
        "authority: {}\n",
        view.record.authority.join(", ")
    ));
    if let Some(old) = &view.record.replaces {
        out.push_str(&format!("replaces: {old}\n"));
    }
    out.push_str("acceptance:\n");
    for (index, condition) in view.record.acceptance.iter().enumerate() {
        out.push_str(&format!("  {}. {}\n", index + 1, condition));
    }
    if let Some(class) = view.failure_class {
        out.push_str(&format!("failure: {}\n", class.plain()));
    }
    if !view.record.notes.is_empty() {
        out.push_str("notes:\n");
        for (index, note) in view.record.notes.iter().enumerate().rev() {
            let id = if note.id.is_empty() {
                format!("undated:{}:note-{:04}", view.record.id, index + 1)
            } else {
                note.id.clone()
            };
            let provenance = if note.request.is_empty() {
                "undated".to_string()
            } else {
                format!(
                    "{} request:{}",
                    &note.at[..note.at.len().min(10)],
                    note.request
                )
            };
            let replaces = note
                .replaces
                .as_deref()
                .map(|old| format!("; replaces {old}"))
                .unwrap_or_default();
            out.push_str(&format!("  {id} [{provenance}{replaces}] {}\n", note.text));
        }
    }
    for evidence in &view.record.installed {
        if let (Some(machine), Some(build)) = (&evidence.machine, &evidence.build) {
            out.push_str(&format!("installed: {machine} runs {build}\n"));
        }
    }
    if running_current(&view.record) {
        if let Some(evidence) = view.record.running.last() {
            out.push_str(&format!(
                "running processes: checked on {} ({})\n",
                evidence.machines.join(", "),
                evidence.processes.join(", ")
            ));
        }
    } else if !view.record.installed.is_empty() {
        out.push_str("running processes: unknown; verification is blocked\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_do_not_overlap_lane_ids() {
        assert!(validate_id("job-0001").is_ok());
        assert!(validate_id("t-0001").is_err());
    }

    #[test]
    fn unreadable_records_keep_their_identity_and_are_never_replaced() {
        let world = crate::scenarios::World::new();
        let project = world.project("demo", "a.sock");
        std::fs::write(dir(&project).join("job-0001.toml"), "not toml").unwrap();
        assert_eq!(next_id(&project).unwrap(), "job-0002");

        let mut wrong = record(&project, "job-0002");
        wrong.id = "job-0003".into();
        std::fs::write(
            dir(&project).join("job-0002.toml"),
            toml::to_string(&wrong).unwrap(),
        )
        .unwrap();
        assert!(format!("{:#}", load(&project, "job-0002").unwrap_err()).contains("task_identity"));
    }

    #[test]
    fn state_lists_must_follow_evidence_order() {
        assert!(validate_states(&["finished".into(), "merged".into(), "verified".into()]).is_ok());
        assert!(
            validate_states(&["finished".into(), "installed".into(), "merged".into()]).is_err()
        );
    }

    fn record(project: &Project, id: &str) -> Task {
        let task = Task {
            id: id.into(),
            title: "Ship the checked change.".into(),
            authority: vec!["request:q-1".into()],
            acceptance: vec!["The command reports the new result.".into()],
            created: project::now(),
            ..Task::default()
        };
        std::fs::create_dir_all(dir(project)).unwrap();
        write(project, &task).unwrap();
        task
    }

    #[test]
    fn generation_waits_for_a_record_and_preserves_a_handwritten_list() {
        let world = crate::scenarios::World::new();
        let project = world.project("demo", "a.sock");
        let handwritten = b"# Tasks\n\n## Notes\n- [ ] Keep this detail (me)\n";
        let tasks_md = project.dir().join("TASKS.md");
        std::fs::write(&tasks_md, handwritten).unwrap();

        refresh_tasks_md(&project).unwrap();
        assert_eq!(std::fs::read(&tasks_md).unwrap(), handwritten);
        assert!(!project.dir().join("memory/archive").exists());

        record(&project, "job-0001");
        refresh_tasks_md(&project).unwrap();
        let generated = std::fs::read_to_string(&tasks_md).unwrap();
        assert!(generated.contains(GENERATED_NOTICE));
        assert!(generated.contains("Previous hand-written task list: `memory/archive/"));
        let archived: Vec<_> = std::fs::read_dir(project.dir().join("memory/archive"))
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .collect();
        assert_eq!(archived.len(), 1);
        assert_eq!(std::fs::read(&archived[0]).unwrap(), handwritten);

        refresh_tasks_md(&project).unwrap();
        let refreshed = std::fs::read_to_string(&tasks_md).unwrap();
        assert!(refreshed.contains("Previous hand-written task list: `memory/archive/"));
        assert_eq!(
            std::fs::read_dir(project.dir().join("memory/archive"))
                .unwrap()
                .count(),
            1
        );
    }

    #[test]
    fn a_missing_request_is_refused() {
        let world = crate::scenarios::World::new();
        let project = world.project("demo", "a.sock");
        let error = add(
            &project,
            "Ship the checked change.",
            vec!["request:q-missing".into()],
            vec!["The command reports the new result.".into()],
            None,
            None,
            None,
        )
        .unwrap_err();
        assert!(format!("{error:#}").contains("no message `q-missing`"));
        assert!(list_with_errors(&project).0.is_empty());
    }

    #[test]
    fn one_record_drives_every_milestone_and_skips_install_when_not_configured() {
        use crate::round::testkit::{commit_file, fixture, git};
        let fx = fixture();
        let ctx = fx.world.ctx();
        crate::plan::set(&ctx, "demo", "command", "It reports the checked result.", 0).unwrap();
        crate::plan::step_add(&ctx, "demo", "Ship the checked change.", vec![], vec![], 1).unwrap();
        let task = record(&fx.project, "job-0001");
        update(&fx.project, "job-0001", |task| {
            task.plan_step = Some("s-1".into());
            Ok(())
        })
        .unwrap();
        assert_eq!(view(&fx.project, task).state, State::Open);

        let (lane, sha) = fx.lane(1);
        link_attempt(&fx.project, "job-0001", &lane).unwrap();
        assert_eq!(
            view(&fx.project, load(&fx.project, "job-0001").unwrap()).state,
            State::Working
        );
        assert!(
            crate::plan::show(&ctx, "demo", false)
                .unwrap()
                .contains("running s-1")
        );
        let digest = crate::coordinator::digest(&ctx, &fx.project, "ha")
            .unwrap()
            .0;
        assert!(digest.contains("job-0001 [working]"));
        fx.seal_done(&lane, 1, 1, &sha, "# report\n");
        assert_eq!(
            view(&fx.project, load(&fx.project, "job-0001").unwrap()).state,
            State::Finished
        );

        crate::round::open(
            &ctx,
            "demo",
            crate::round::OpenArgs {
                round: "r1".into(),
                branch: "main".into(),
                plain: Some("The checked change is ready.".into()),
                repo: Some(fx.repo.to_string_lossy().into_owned()),
            },
        )
        .unwrap();
        crate::round::admit(&ctx, "demo", "r1", &lane).unwrap();
        let review = crate::round::review(&ctx, "demo", "r1").unwrap();
        git(&review.worktree, &["merge", "-q", "--no-edit", &sha]);
        let candidate = git(&review.worktree, &["rev-parse", "HEAD"]);
        let round = crate::round::load(&fx.project, "r1").unwrap();
        let verdict_text = format!(
            "+++\nverdict = \"MERGE\"\nround = \"r1\"\ncandidate = \"{candidate}\"\nmanifest_hash = \"{}\"\npolicy_hash = \"{}\"\ngates = []\n+++\n\nAll gates pass.\n",
            round.manifest_hash.unwrap(),
            round.policy_hash
        );
        let verdict = commit_file(
            &review.worktree,
            &crate::round::verdict_path("r1"),
            &verdict_text,
            "verdict",
        );
        let reviewer = fx.thread("Reviewer");
        fx.seal_done(&reviewer, 1, 1, &verdict, "# verdict\n");
        crate::round::bind_reviewer(&ctx, "demo", "r1", &reviewer).unwrap();
        crate::round::advance(&ctx, "demo").unwrap();
        assert_eq!(
            view(&fx.project, load(&fx.project, "job-0001").unwrap()).state,
            State::Reviewed
        );
        crate::round::merge(&ctx, "demo", "r1", None).unwrap();
        let merged = view(&fx.project, load(&fx.project, "job-0001").unwrap());
        assert_eq!(merged.state, State::Merged);
        assert_eq!(merged.next, "none");
        // This repository inherits a workflow with no install state.
        assert!(
            !required_states(&fx.project, &merged.record)
                .unwrap()
                .iter()
                .any(|state| state == "installed")
        );

        let (mut settings, body) = fx.project.read_project_md().unwrap();
        settings.task_states = STATES.iter().map(|state| state.to_string()).collect();
        let front = toml::to_string(&settings).unwrap();
        std::fs::write(
            fx.project.project_md(),
            format!("+++\n{front}+++\n\n{body}"),
        )
        .unwrap();
        let installed = record_installed(
            &fx.project,
            "job-0001",
            "local",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        )
        .unwrap();
        assert_eq!(view(&fx.project, installed).state, State::Installed);
        record_running(
            &fx.project,
            "job-0001",
            vec!["local".into()],
            vec!["local:ticker:running".into()],
        )
        .unwrap();
        let verified = record_evidence(
            &fx.project,
            "job-0001",
            EvidenceKind::Verified,
            "ha doctor",
            vec![1],
        )
        .unwrap();
        assert_eq!(view(&fx.project, verified).state, State::Verified);
        assert!(
            crate::plan::show(&ctx, "demo", false)
                .unwrap()
                .contains("done    s-1")
        );
        let overview = crate::talk::overview::Overview::load(
            &fx.project,
            &crate::talk::Journal::default(),
            &crate::talk::view::Conversation::default(),
            &crate::talk::overview::Live::default(),
        );
        assert!(
            overview
                .tasks
                .iter()
                .any(|row| row.prefix == "verified" && row.marker == "job-0001")
        );

        refresh_tasks_md(&fx.project).unwrap();
        let generated = std::fs::read_to_string(fx.project.dir().join("TASKS.md")).unwrap();
        assert!(generated.contains("job-0001` Ship the checked change. — verified"));
    }

    #[test]
    fn adopt_links_a_historical_thread_and_its_round_and_refuses_reuse() {
        use crate::round::testkit::fixture;
        let fx = fixture();
        let mut task = record(&fx.project, "job-0001");
        task.repo = Some(fx.repo.to_string_lossy().into_owned());
        write(&fx.project, &task).unwrap();
        let (lane, _sha) = fx.lane(1);
        crate::thread::update(&fx.project, &lane, |thread| {
            thread.repo = fx.repo.to_string_lossy().into_owned();
        })
        .unwrap();
        crate::round::open(
            &fx.world.ctx(),
            "demo",
            crate::round::OpenArgs {
                round: "r1".into(),
                branch: "main".into(),
                plain: Some("The historical change is reviewed.".into()),
                repo: Some(fx.repo.to_string_lossy().into_owned()),
            },
        )
        .unwrap();
        crate::round::admit(&fx.world.ctx(), "demo", "r1", &lane).unwrap();

        let adopted = adopt(&fx.project, "job-0001", &lane).unwrap();
        assert_eq!(adopted.attempts.as_slice(), std::slice::from_ref(&lane));
        assert_eq!(adopted.rounds, ["r1"]);

        let mut second = record(&fx.project, "job-0002");
        second.repo = Some(fx.repo.to_string_lossy().into_owned());
        write(&fx.project, &second).unwrap();
        let error = adopt(&fx.project, "job-0002", &lane).unwrap_err();
        assert!(error.to_string().contains("task_adopt_linked"), "{error:#}");
    }

    #[test]
    fn adopt_refuses_a_thread_from_another_repository() {
        let world = crate::scenarios::World::new();
        let project = world.project("demo", "a.sock");
        let mut task = record(&project, "job-0001");
        task.repo = Some("/expected/repository".into());
        write(&project, &task).unwrap();
        let thread = crate::thread::allocate(&project, |thread| {
            thread.repo = "/other/repository".into();
        })
        .unwrap();
        let error = adopt(&project, "job-0001", &thread.id).unwrap_err();
        assert!(
            error.to_string().contains("task_adopt_repository"),
            "{error:#}"
        );
    }

    #[test]
    fn waiting_attempt_says_that_its_next_step_is_rolf() {
        use crate::round::testkit::fixture;
        let fx = fixture();
        record(&fx.project, "job-0001");
        let (lane, _) = fx.lane(1);
        link_attempt(&fx.project, "job-0001", &lane).unwrap();
        fx.seal_waiting(&lane, 1, 1, "Choose the final colour.");

        let waiting = view(&fx.project, load(&fx.project, "job-0001").unwrap());
        assert_eq!(waiting.state, State::Working);
        assert_eq!(waiting.next, "wait for Rolf: Choose the final colour.");
    }

    #[test]
    fn provider_failure_keeps_its_class_and_is_not_finished() {
        let world = crate::scenarios::World::new();
        let project = world.project("demo", "a.sock");
        record(&project, "job-0001");
        let thread = crate::thread::allocate(&project, |thread| {
            thread.status = crate::thread::Status::Failed;
            thread.attempt = 1;
            thread.failure_class = FailureClass::Provider;
            thread.provider_failure_kind = Some("pi".into());
        })
        .unwrap();
        link_attempt(&project, "job-0001", &thread.id).unwrap();
        let view = view(&project, load(&project, "job-0001").unwrap());
        assert_eq!(view.state, State::Failed);
        assert_eq!(view.failure_class, Some(FailureClass::Provider));
        assert_eq!(view.provider_kind.as_deref(), Some("pi"));
    }
}
